

/*
--EJEMPLO DE PARTICION DE TABLA 
SELECT S.*, ROW_NUMBER () OVER(PARTITION BY CODIGO, MES_ALTA, cd_subproducto, cd_canal_venta, cd_divisa 
								ORDER BY CODIGO, MES_ALTA, cd_subproducto, cd_canal_venta, cd_divisa DESC) AS ROW
FROM [dbo].[BD_TB_SEGURO] AS S
WHERE CODIGO = '8000001421'
*/


-- CAMBIUAMOS EL FORMATO DE LAS FECHAS QUE ESTAN EN STRING POR FECHA
ALTER TABLE [BD_TB_SEGURO] ALTER COLUMN [fh_apertura]
nvarchar(10);

-- CAMBIUAMOS EL FORMATO DE LAS FECHAS QUE ESTAN EN STRING POR FECHA
   

--CREAMOS LA PRIMERA TABLA TEMPORAL, ES LA MISMA FACT PERO CON INDICE DEL ROW_NUMBER
IF EXISTS (SELECT * FROM sys.tables WHERE NAME = 'Seguro_1')
DROP TABLE [BD_SEGUROS].[dbo].[Seguro_1]

SELECT S.*, ROW_NUMBER () OVER(	ORDER BY CODIGO, MES_ALTA, cd_subproducto, cd_canal_venta, cd_divisa, MES_CORTE DESC) AS ROW
INTO [BD_SEGUROS].[dbo].[Seguro_1]
FROM [BD_SEGUROS].[dbo].[BD_TB_SEGURO] AS S
--WHERE CODIGO = '8000001421'


--CREAR VISTA DE LLAVE DE FACT Y DIA DE HOY
USE [BD_SEGUROS];
GO
CREATE OR ALTER  VIEW vw_fact_seguro_today AS
SELECT CODIGO, MES_ALTA, cd_subproducto, cd_canal_venta, cd_divisa, MES_CORTE,
CONVERT (date, GETDATE()) AS TODAY
, ROW_NUMBER () OVER(	ORDER BY CODIGO, MES_ALTA, cd_subproducto, cd_canal_venta, cd_divisa, MES_CORTE DESC) AS VW_ROW
FROM [dbo].[BD_TB_SEGURO] AS S;
GO

-- SELECT * FROM vw_fact_seguro_today

-- ACA CRUZAREMOS [Seguro_1] y la vista 'vw_fact_seguro_today'
IF EXISTS (SELECT * FROM sys.tables WHERE NAME = 'Seguro_2')
DROP TABLE [BD_SEGUROS].[dbo].[Seguro_2]

SELECT S.*, V.TODAY
INTO [BD_SEGUROS].[dbo].[Seguro_2]
FROM [BD_SEGUROS].[dbo].[Seguro_1] AS S
LEFT JOIN vw_fact_seguro_today AS V
	ON S.ROW = V.VW_ROW

--SELECT * FROM [BD_SEGUROS].[dbo].[Seguro_2]

-- CAMBIAR LOS NULL POR '' 
IF EXISTS (SELECT * FROM sys.tables WHERE NAME = 'Seguro_3')
DROP TABLE [BD_SEGUROS].[dbo].[Seguro_3]

SELECT S.*,
ISNULL(S.FH_VENCIMIENTO, '') AS FH_VENCIMIENTO2
INTO [BD_SEGUROS].[dbo].[Seguro_3]
FROM [BD_SEGUROS].[dbo].[Seguro_2] AS S


--SELECT * FROM [BD_SEGUROS].[dbo].[Seguro_3]
-- HASTA ACA ESTA BIEN 



-- DESPUES DE REEMPLAZAR POR NULOS 
-- FILTRANDO  LOS '' 
-- ACA EN  AÑADIMOS UNA NUEVA COLUMNA REEMPLAZANDO EL STRING POR DATE
IF EXISTS (SELECT * FROM sys.tables WHERE NAME = 'Seguro_4')
DROP TABLE [BD_SEGUROS].[dbo].[Seguro_4]

SELECT N.*
,CONVERT(date, CONCAT(SUBSTRING(N.FH_APERTURA, 7, 4), '-', SUBSTRING(N.FH_APERTURA, 4, 2), '-', SUBSTRING(N.FH_APERTURA, 1, 2)), 23) AS F_APERTURA
,CONVERT(date, CONCAT(SUBSTRING(N.FH_VENCIMIENTO2, 7, 4), '-', SUBSTRING(N.FH_VENCIMIENTO2, 4, 2), '-', SUBSTRING(N.FH_VENCIMIENTO2, 1, 2)), 23) AS F_VENCIMIENTO

INTO [BD_SEGUROS].[dbo].[Seguro_4]
FROM [BD_SEGUROS].[dbo].[Seguro_3] AS N
WHERE  NOT (N.FH_VENCIMIENTO = '')  


-- REEMPLAZAR '' POR TODAY
-- FILTRANDO  LOS NO '' 
-- ACA EN  AÑADIMOS UNA NUEVA COLUMNA REEMPLAZANDO A LOS '' POR TODAY 
IF EXISTS (SELECT * FROM sys.tables WHERE NAME = 'Seguro_5')
DROP TABLE [BD_SEGUROS].[dbo].[Seguro_5]

SELECT N.*
,CONVERT(date, CONCAT(SUBSTRING(N.FH_APERTURA, 7, 4), '-', SUBSTRING(N.FH_APERTURA, 4, 2), '-', SUBSTRING(N.FH_APERTURA, 1, 2)), 23) AS F_APERTURA
, CASE WHEN N.FH_VENCIMIENTO2 = '' THEN N.TODAY
			END F_VENCIMIENTO
INTO [BD_SEGUROS].[dbo].[Seguro_5]
FROM [BD_SEGUROS].[dbo].[Seguro_3] AS N
WHERE  N.FH_VENCIMIENTO = ''


-- UNIMOS [BD_SEGUROS].[dbo].[Seguro_4]   Y  [BD_SEGUROS].[dbo].[Seguro_5]
IF EXISTS (SELECT * FROM sys.tables WHERE NAME = 'Seguro_6')
DROP TABLE [BD_SEGUROS].[dbo].[Seguro_6]

SELECT * 
INTO [BD_SEGUROS].[dbo].[Seguro_6]
FROM [BD_SEGUROS].[dbo].[Seguro_4]
UNION  
SELECT * FROM [BD_SEGUROS].[dbo].[Seguro_5]

--CREAMOS LA MEDIDA DE YEAR_DIF
IF EXISTS (SELECT * FROM sys.tables WHERE NAME = 'Seguro_7')
DROP TABLE [BD_SEGUROS].[dbo].[Seguro_7]

SELECT *, 
DATEDIFF (YEAR, F_APERTURA, F_VENCIMIENTO) AS YEAR_DIF
INTO [BD_SEGUROS].[dbo].[Seguro_7]
FROM  [BD_SEGUROS].[dbo].[Seguro_6]


--

--CONVERT(INT,'5678') AS Result;
--CAST('1234' AS INT) AS Result;
--CONVERTIMOS LAS MEDIDAS DE STRING A FLOAT E INSERTAMOS A LA TABLA FINAL
IF EXISTS (SELECT * FROM sys.tables WHERE NAME = 'Seguro_F')
DROP TABLE [BD_SEGUROS].[dbo].[Seguro_F]

SELECT M.CODIGO, M.MES_CORTE, M.MES_ALTA, M.cd_subproducto, m.cd_canal_venta, m.cd_divisa, 
m.ROW, m.F_APERTURA, m.F_VENCIMIENTO, M.YEAR_DIF
,CONVERT(float, IM_PRIMA) AS im_prima
,CONVERT(float, M.im_capital_aseg) AS im_capital_aseg
,CONVERT(float, M.im_comision) AS im_comision
INTO [BD_SEGUROS].[dbo].[Seguro_F]
FROM [BD_SEGUROS].[dbo].[Seguro_7] as M


--INSERTAMOS LA TABLA FINAL A DWH 
SELECT * 
INTO [DWH_ProjectCubos_seguros].[dbo].[Seguro]
FROM [BD_SEGUROS].[dbo].[Seguro_F]



